### ISSUE TITLE
Shortcut will be applied in all opened XRM tool box Opened Windows

### ISSUE THREAD

**Issue by aboodh95** [Innofactor/PluginRegistration#25] opened 2017-03-04 05:12 UTC
Hi
you make some shortcuts like CTRL-A will open register new Plugin
the issue is that the XRM tool box will catch the key input in all open windows 
for example i'm in Web Resource Management and i need to select the code but when i press CTRL-A
your New Plugin Registration Will Popup 
So If you can check this issue

**Comment by rappen** [comment] 2017-03-04 09:40
Duplicate of #8 and https://github.com/MscrmTools/XrmToolBox/issues/479 and probably some more issues for various plugins.
This is a toolbox issue, that is still being evaluated for options how to solve it.

**Closed by rappen** 2017-03-04 09:40 UTC

**Comment by aboodh95** [comment] 2017-03-04 10:31
You can solve it by checking if your plugin is the active tap in the app

**Comment by shytikov** [comment] 2017-03-04 15:32
This an idea BTW. Not sure is it feasible to implement easily, but it should be event handler, that fires for all shourtcut calls... and there we can try to check `sender` of the message, if it's another plugin — abort.

Although all other plugins needs to do the same of course.

**Comment by shytikov** [comment] 2017-03-04 15:33
We can implement this in a plugin base class!
