### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by Volkanboz** [Innofactor/PluginRegistration#51] opened 2019-05-02 08:24 UTC
Hello,

I already checked the other tickets but I couldn't find the solution of my problem.
When we load assemblies in Plugin Registration Tool, we have the following error:

An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
   at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.LoadNodes(ICrmTreeNode[] rootNodes)
   at Xrm.Sdk.PluginRegistration.MainControl.LoadNodes(CrmViewType view)

The problem is that we don't know which assembly creates the issue, I already checked if there were any duplicate assemblies but i couldn't find.
For info, with SDK Plugin Registration Tool, it is working well...
Any idea?

**Comment by imranakram** [comment] 2019-05-02 08:39
Hard to tell at the moment. Which version of CRM are you using and what versions of SDK are the assemblies dependent on? Which version of Plugin Registration Tool are you using?

**Comment by Volkanboz** [comment] 2019-05-02 08:58
Hi imranakram,

Plugin registration tool version (last version): 3.2018.8.3
Dynamics 365: Version 1710 (9.1.0.4048) online
SDK version: 9.0.0.0

**Comment by imranakram** [comment] 2019-05-02 09:18
It worked fine with Dynamics 365 Version 1710 (9.1.0.4233) online. Unfortunately, I don't have an environment with Version 1710 (9.1.0.4048) at my disposal at the moment.

**Comment by Volkanboz** [comment] 2019-05-02 09:27
Can't we have any info regarding the assembly which triggers the error? Usually what the error means? That an assembly is duplicated?

**Comment by Volkanboz** [comment] 2019-05-02 09:29
I don't think it is related to the version of the environment because on another environment with same version, it works fine with different assemblies.

**Comment by imranakram** [comment] 2019-05-02 11:46
Thanks, 
If you try to register the same assembly again, you do get an exception that states:

```
Unhandled Exception: System.ServiceModel.FaultException

Plug-in assembly fullnames must be unique (ignoring the version build and revision number).
```
If that's what you mean by "duplicate assemblies"

**Comment by Volkanboz** [comment] 2019-05-02 11:55
ah so this can be not related to duplicated assemblies then.
What it can be then? The error appears when Plugin Registration is trying to load all assemblies:

An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.LoadNodes(ICrmTreeNode[] rootNodes)
at Xrm.Sdk.PluginRegistration.MainControl.LoadNodes(CrmViewType view)

**Comment by imranakram** [comment] 2020-01-03 17:38
Closing this because I'n unable to reproduce it so far unfortunately

**Closed by imranakram** 2020-01-03 17:38 UTC

**Comment by AngelRodriguez8008** [comment] 2020-01-07 20:17
I have the same Error. How can I help? Should I debug the Project? I have no experience with XrmToolBox Plugins development. But maybe some tests that can be run independently?
