### ISSUE TITLE
Filtering Attributes required on CREATE message

### ISSUE THREAD

**Issue by aovar** [Innofactor/PluginRegistration#122] opened 2023-10-06 15:46 UTC
Steps to reproduce:
   Register a new Plugin Assembly containing a single Plugin
   Attempt to register a new Step for CREATE message of an entity

Issue
    "Filtering Attributes" is required by the tool
![Screenshot 2023-10-06 174327](https://github.com/Innofactor/PluginRegistration/assets/35955914/c2428781-37da-4ff6-8e3f-f85fa9fa6316)

Expected Behavior
    "Filtering Attributes" is not required for CREATE message of an entity

---
- Deployment: Online
- DB Version: 9.2.23091.190
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.9.66
- Tool Version: 3.2023.9.3

**Comment by imranakram** [comment] 2023-10-09 12:49
Hi, @aovar I'm unable to reproduce this unfortunately.

**Comment by imranakram** [comment] 2023-10-12 07:16
Fixed in version `3.2023.10.2`

**Closed by imranakram** 2023-10-12 07:16 UTC
