### ISSUE TITLE
Deleting a plugin will prevent updating the Assembly 

### ISSUE THREAD

**Issue by aboodh95** [Innofactor/PluginRegistration#48] opened 2018-12-16 12:33 UTC
Hi,

in case i deleted a plug-in then i tried to update the assembly i will have message showing that the deleted plug-in is missing from the dll, i delete it

**Comment by rappen** [comment] 2018-12-16 14:48
Try hitting Refresh, then updating the assembly.
[workaround, still agree issue should be solved]

**Comment by aboodh95** [comment] 2018-12-16 14:51
Ya, refreshing will solve the issue, but as you say it should be fixed

**Comment by imranakram** [comment] 2018-12-17 09:38
Thanks, I'm working on that. I've a solution which solves the issue but its quite slow so I'm trying to find a more efficient solution instead. Duplicate of #38 #14.

**Comment by imranakram** [comment] 2019-07-14 05:53
This is finally fixed in release v3.2019.7.1.

**Closed by imranakram** 2019-07-14 05:53 UTC
Labels: bug
