### ISSUE TITLE
Error when attempting to sort by Entity

### ISSUE THREAD

**Issue by daryllabar** [Innofactor/PluginRegistration#56] opened 2019-08-29 16:57 UTC
When attempting to view by entity (ctrl+Shift+e) I receive the following error:

Unhandled Exception: System.SystemException

The given key was not present in the dictionary.

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Xrm.Sdk.PluginRegistration.MainControl.CreateCrmTreeNodes(CrmViewType view, Guid messageId, Guid messageEntityId, Boolean addToTree)
   at Xrm.Sdk.PluginRegistration.MainControl.LoadNodes(CrmViewType view)

**Comment by imranakram** [comment] 2020-01-03 13:11
Duplicate of #60 #58. I haven't been able to reproduce this so far. Please checkout my comment on #60

**Closed** 2020-01-31 10:31 UTC
