### ISSUE TITLE
Plugin Registration toll

### ISSUE THREAD

**Issue by bipinshan** [Innofactor/PluginRegistration#34] opened 2018-01-19 07:24 UTC
I am not able to register Service Endpoint.
 CRM online 365

**Comment by rappen** [comment] 2018-01-19 07:35
That is correct.
The PRT for XrmToolBox is based on the latest released source code from Microsoft, and from SDK 6.0 and onwards they have not released it.
We are all sorry about that, and have encouraged MS to release current source.

**Comment by bipinshan** [comment] 2018-01-19 07:41
Thank you for the confirmation.

**Comment by rappen** [comment] 2020-09-22 20:13
Closing, duplicate of #36

**Closed by rappen** 2020-09-22 20:13 UTC
Labels: enhancement
